version: "3.8"

services:

  mysql-database:
    image: mysql:latest
    container_name: mysql-jumbo-test
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: jumbo
      MYSQL_USER: jumbo
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456   
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks: 
      - test-network 
      
  jumbo-store-service:
    image: tugayesilyurt/jumbo-store-service
    container_name: jumbo-store-service
    build: 
       context: ./jumbo-store-service
       dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-database
    networks: 
      - test-network   


volumes:
  mysql-data:
      driver: local
      
networks: 
  test-network:
    driver: bridge